// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxrbrccemfzwvbeyarbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4cmJyY2NlbWZ6d3ZiZXlhcmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MjYwMzMsImV4cCI6MjA4NjEwMjAzM30.g0f0T-FoJJFt4YdeYLHkVjsvI4E7dbO-qgl6K2nrEd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});